language: node_js
node_js:
  - "stable"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm update -g npm"
  - "npm install -g bower grunt-cli && bower install"
after_success:
  - grunt sonarRunner
